server:
    host: '0.0.0.0'
    port: 8080
    debug: True
    environment: development
    testing: False
    use_reloader: True

api:
    specs:
        - path: dind.yaml
          append: null
          add_operation_fields:
              x-openapi-router-controller: controllers
          connexion:
              strict_validation: True
              validate_responses: False
              options:
                  swagger_ui: True
                  serve_spec: True
