apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - args:
    - --dockerfile=/file/trs-filer/Dockerfile
    - --destination=docker.io/akash7778/broker:v0.1.1
    - --context=/file/trs-filer/
    image: gcr.io/kaniko-project/executor:v0.22.0
    name: kaniko
    volumeMounts:
    - mountPath: /file
      name: task-pv-storage
    - mountPath: /kaniko/.docker/
      name: task-pv-storage
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
